-- Consolidated qhorus core schema for devtown @QuarkusTest.
-- WHY THIS EXISTS: The real qhorus migrations (db/qhorus/migration/V1-V26) are excluded
-- from the devtown test Flyway instance to avoid V2000 version collision with
-- V2000__message_ledger_entry.sql (casehub-ledger schema). This migration consolidates
-- ALL qhorus schema elements (V1, V3-V26) that Hibernate needs at test time.
--
-- DO NOT EDIT THIS FILE TO ADD NEW QHORUS FEATURES. Instead:
-- 1. Add the real migration to casehub-qhorus runtime/src/main/resources/db/qhorus/migration/
-- 2. Rebuild this consolidation by re-reading all qhorus migrations
--
-- Compatible with H2 (test) and PostgreSQL (production).

-- -------------------------------------------------------------------------
-- Channel
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel (
    id                     UUID         NOT NULL,
    name                   VARCHAR(255) NOT NULL,
    description            VARCHAR(1000),
    semantic               VARCHAR(50)  NOT NULL,
    barrier_contributors   TEXT,
    created_at             TIMESTAMP    NOT NULL,
    last_activity_at       TIMESTAMP    NOT NULL,
    -- V3: paused flag for HITL flow control
    paused                 BOOLEAN      NOT NULL DEFAULT FALSE,
    -- V5: ACL write permissions
    allowed_writers        TEXT,
    -- V6: admin role
    admin_instances        TEXT,
    -- V7: rate limiting
    rate_limit_per_channel INTEGER,
    rate_limit_per_instance INTEGER,
    -- V12: message type filtering
    allowed_types          TEXT,
    -- V15: auto-creation flag
    auto_created           BOOLEAN      NOT NULL DEFAULT FALSE,
    -- V16: denied message types
    denied_types           TEXT,
    -- V18: multi-tenancy
    tenancy_id             VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    CONSTRAINT pk_channel PRIMARY KEY (id),
    -- V17: slug format constraint (H2 compatible — REGEXP_LIKE instead of SIMILAR TO)
    CONSTRAINT chk_channel_name_slug
        CHECK (REGEXP_LIKE(name, '^[a-z][a-z0-9]*(-[a-z0-9]+)*(/[a-z][a-z0-9]*(-[a-z0-9]+)*)*$')
               AND LENGTH(name) <= 200),
    -- V18: tenancy-scoped uniqueness (replaces V1 uq_channel_name)
    CONSTRAINT uq_channel_name_tenancy UNIQUE (tenancy_id, name)
);

-- -------------------------------------------------------------------------
-- Instance (agent presence registry)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS instance (
    id                  UUID         NOT NULL,
    instance_id         VARCHAR(255) NOT NULL,
    description         VARCHAR(1000),
    status              VARCHAR(50)  NOT NULL DEFAULT 'online',
    claudony_session_id VARCHAR(255),
    session_token       VARCHAR(255),
    last_seen           TIMESTAMP    NOT NULL,
    registered_at       TIMESTAMP    NOT NULL,
    -- V8: read-only flag
    read_only           BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_instance PRIMARY KEY (id),
    CONSTRAINT uq_instance_instance_id UNIQUE (instance_id)
);

-- -------------------------------------------------------------------------
-- Capability (capability tags per instance)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS capability (
    id          UUID         NOT NULL,
    instance_id UUID         NOT NULL,
    tag         VARCHAR(255) NOT NULL,
    CONSTRAINT pk_capability PRIMARY KEY (id),
    CONSTRAINT fk_capability_instance FOREIGN KEY (instance_id) REFERENCES instance(id)
);

-- -------------------------------------------------------------------------
-- Message (sequence PK preserves ordering)
-- -------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS message_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS message (
    id              BIGINT       NOT NULL,
    channel_id      UUID         NOT NULL,
    sender          VARCHAR(255) NOT NULL,
    message_type    VARCHAR(50)  NOT NULL,
    content         TEXT,
    correlation_id  VARCHAR(255),
    in_reply_to     BIGINT,
    reply_count     INT          NOT NULL DEFAULT 0,
    artefact_refs   TEXT,
    created_at      TIMESTAMP    NOT NULL,
    -- V9: actor type (human vs AI)
    actor_type      VARCHAR(10)  NOT NULL DEFAULT 'HUMAN',
    -- V12: deadline for obligation discharge
    deadline        TIMESTAMP,
    -- V12: explicit acknowledgment timestamp
    acknowledged_at TIMESTAMP,
    -- V13: link to commitment table
    commitment_id   UUID,
    -- V19: multi-tenancy
    tenancy_id      VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    -- V26: version counter for LAST_WRITE detection
    version         INT          NOT NULL DEFAULT 0,
    CONSTRAINT pk_message PRIMARY KEY (id),
    CONSTRAINT fk_message_channel FOREIGN KEY (channel_id) REFERENCES channel(id),
    CONSTRAINT fk_message_reply FOREIGN KEY (in_reply_to) REFERENCES message(id)
);

-- V11: composite index for per-channel timeline scans
CREATE INDEX IF NOT EXISTS idx_message_channel_id ON message (channel_id, id);

-- -------------------------------------------------------------------------
-- Commitment (obligation lifecycle for QUERY and COMMAND)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS commitment (
    id                   UUID         NOT NULL,
    correlation_id       VARCHAR(255) NOT NULL,
    channel_id           UUID         NOT NULL,
    message_type         VARCHAR(50)  NOT NULL,
    requester            VARCHAR(255) NOT NULL,
    obligor              VARCHAR(255),
    state                VARCHAR(50)  NOT NULL DEFAULT 'OPEN',
    expires_at           TIMESTAMP,
    acknowledged_at      TIMESTAMP,
    resolved_at          TIMESTAMP,
    delegated_to         VARCHAR(255),
    parent_commitment_id UUID,
    created_at           TIMESTAMP    NOT NULL,
    -- V20: multi-tenancy
    tenancy_id           VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    CONSTRAINT pk_commitment        PRIMARY KEY (id),
    CONSTRAINT fk_commitment_channel FOREIGN KEY (channel_id)           REFERENCES channel(id),
    CONSTRAINT fk_commitment_parent  FOREIGN KEY (parent_commitment_id) REFERENCES commitment(id)
);

-- V10: base indices
CREATE INDEX IF NOT EXISTS idx_commitment_correlation_id ON commitment (correlation_id);
CREATE INDEX IF NOT EXISTS idx_commitment_channel_id     ON commitment (channel_id);
CREATE INDEX IF NOT EXISTS idx_commitment_state_expires  ON commitment (state, expires_at);
-- V22: obligor index for CommitmentStore.findOpenByObligor()
CREATE INDEX IF NOT EXISTS idx_commitment_obligor ON commitment (obligor);

-- -------------------------------------------------------------------------
-- Shared Data (artefact store)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shared_data (
    id          UUID         NOT NULL,
    data_key    VARCHAR(255) NOT NULL,
    content     TEXT,
    created_by  VARCHAR(255),
    description VARCHAR(1000),
    complete    BOOLEAN      NOT NULL DEFAULT TRUE,
    size_bytes  BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_shared_data PRIMARY KEY (id),
    CONSTRAINT uq_shared_data_key UNIQUE (data_key)
);

-- -------------------------------------------------------------------------
-- Artefact Claim (claim/release lifecycle for GC)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS artefact_claim (
    id          UUID      NOT NULL,
    artefact_id UUID      NOT NULL,
    instance_id UUID      NOT NULL,
    claimed_at  TIMESTAMP NOT NULL,
    CONSTRAINT pk_artefact_claim PRIMARY KEY (id),
    CONSTRAINT fk_artefact_claim_data FOREIGN KEY (artefact_id) REFERENCES shared_data(id),
    CONSTRAINT fk_artefact_claim_instance FOREIGN KEY (instance_id) REFERENCES instance(id)
);

-- -------------------------------------------------------------------------
-- Watchdog (condition-based alerting, optional module)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS watchdog (
    id                   UUID         NOT NULL,
    condition_type       VARCHAR(50)  NOT NULL,
    target_name          VARCHAR(255) NOT NULL,
    threshold_seconds    INT,
    threshold_count      INT,
    notification_channel VARCHAR(255) NOT NULL,
    created_by           VARCHAR(255),
    created_at           TIMESTAMP    NOT NULL,
    last_fired_at        TIMESTAMP,
    -- V21: multi-tenancy
    tenancy_id           VARCHAR(255) NOT NULL DEFAULT '278776f9-e1b0-46fb-9032-8bddebdcf9ce',
    CONSTRAINT pk_watchdog PRIMARY KEY (id)
);

-- -------------------------------------------------------------------------
-- Channel Connector Binding (bi-directional routing)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channel_connector_binding (
    channel_id            UUID         NOT NULL,
    inbound_connector_id  VARCHAR(64)  NOT NULL,
    external_key          VARCHAR(255) NOT NULL,
    outbound_connector_id VARCHAR(64)  NOT NULL,
    outbound_destination  VARCHAR(512) NOT NULL,
    CONSTRAINT pk_channel_connector_binding PRIMARY KEY (channel_id),
    CONSTRAINT fk_binding_channel FOREIGN KEY (channel_id) REFERENCES channel(id),
    CONSTRAINT uq_binding_key UNIQUE (inbound_connector_id, external_key)
);

-- -------------------------------------------------------------------------
-- Delivery Cursor (outbound message delivery tracking)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS delivery_cursor (
    id                      UUID      DEFAULT random_uuid() PRIMARY KEY, -- H2 compatible (not gen_random_uuid())
    channel_id              UUID      NOT NULL,
    backend_id              VARCHAR(255) NOT NULL,
    last_delivered_id       BIGINT,
    last_delivered_version  INT       NOT NULL DEFAULT 0, -- V26: version tracking
    updated_at              TIMESTAMP,
    created_at              TIMESTAMP NOT NULL DEFAULT current_timestamp(), -- H2 compatible (not now())
    CONSTRAINT uq_delivery_cursor_channel_backend UNIQUE (channel_id, backend_id),
    CONSTRAINT fk_delivery_cursor_channel FOREIGN KEY (channel_id) REFERENCES channel(id) ON DELETE CASCADE
);
